ShoppingCart.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using ShoppingCart.Web.Models;
using ShoppingCart.Web.Service.IService;
using ShoppingCart.Web.Utility;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;



namespace ShoppingCart.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProviderService _tokenProviderService;
        public AuthController(IAuthService authService, ITokenProviderService tokenProviderService)
        {
            _authService = authService;
            _tokenProviderService = tokenProviderService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDto loginRequestDto = new LoginRequestDto();
            return View(loginRequestDto);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDto loginRequestDto)
        {
            ResponseDto result = await _authService.LoginAsync(loginRequestDto);
            if (result != null && result.IsSuccess)
            {
                LoginResponseDto loginResponseDto = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(result.Result));
                await SignInUser(loginResponseDto);
                _tokenProviderService.SetToken(loginResponseDto.Token);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["error"] = result.Message;
                return View(loginRequestDto);
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
            new SelectListItem{Text=StaticData.RoleAdmin,Value=StaticData.RoleAdmin},
                     new SelectListItem{Text=StaticData.RoleCustomer,Value=StaticData.RoleCustomer},

            };
            ViewBag.RoleList = roleList;
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="registrationRequest"></param>
        /// <returns></returns>

        [HttpPost]
        public async Task<IActionResult> Register(RegistrationRequestDto registrationRequest)
        {
            ResponseDto result = await _authService.RegisterAsync(registrationRequest);
            ResponseDto assignRole;
            if (result != null && result.IsSuccess)
            {
                if (string.IsNullOrEmpty(registrationRequest.Role))
                {
                    registrationRequest.Role = StaticData.RoleCustomer;
                }
                assignRole = await _authService.AssignRoleAsync(registrationRequest);

                if (assignRole != null && assignRole.IsSuccess)
                {
                    TempData["success"] = "Registration Successful";
                    return RedirectToAction(nameof(Login));
                }
            }

            var roleList = new List<SelectListItem>()
            {
            new SelectListItem{Text=StaticData.RoleAdmin,Value=StaticData.RoleAdmin},
                     new SelectListItem{Text=StaticData.RoleCustomer,Value=StaticData.RoleCustomer},

            };
            ViewBag.RoleList = roleList;
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            _tokenProviderService.ClearToken();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        private async Task SignInUser(LoginResponseDto loginResponseDto)
        {
            var handler = new JwtSecurityTokenHandler();
            var jwtToken = handler.ReadJwtToken(loginResponseDto.Token);
            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, jwtToken.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, jwtToken.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, jwtToken.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));

            identity.AddClaim(new Claim(ClaimTypes.Name, jwtToken.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(ClaimTypes.Role, jwtToken.Claims.FirstOrDefault(u => u.Type == "role").Value));
            
            var claimsPrincipal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);
        }
    }
}

ShoppingCart.Web/Controllers/CouponController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ShoppingCart.Web.Models;
using ShoppingCart.Web.Service.IService;

namespace ShoppingCart.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService=couponService;
        }
        public async Task<IActionResult> Index()
        {
            List<CouponsDto>? list = new();
            ResponseDto? responseDto = await _couponService.GetAllCouponAsync();
            if (responseDto!=null && responseDto.IsSuccess)
            {
                list=JsonConvert.DeserializeObject<List<CouponsDto>>(Convert.ToString(responseDto.Result));
            }
            else
            {
                TempData["error"] = responseDto.Message;
            }
            return View(list);
        }

        public async Task<IActionResult> Create()
        {
            CouponsDto couponsDto = new CouponsDto();
            return View(couponsDto);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CouponsDto couponsDto)
        {
            couponsDto.CouponPicture = new byte[0];
            ResponseDto? responseDto = await _couponService.CreateCouponAsync(couponsDto);
            if(responseDto !=null && responseDto.IsSuccess)
            {
                TempData["success"] = responseDto?.Message;
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = responseDto.Message;
            }
            return View(couponsDto);
        }

        public async Task<IActionResult> Details(int id)
        {
            CouponsDto? objCouponsDto = new();
            ResponseDto? responseDto = await _couponService.GetCouponByIdAsync(id);
            if (responseDto != null && responseDto.IsSuccess)
            {
                objCouponsDto = JsonConvert.DeserializeObject<CouponsDto>(Convert.ToString(responseDto.Result));
            }
            else
            {
                TempData["error"] = responseDto.Message;
            }
            return View(objCouponsDto);
        }

        public async Task<IActionResult> Edit(int id)
        {
            CouponsDto? objCouponsDto = new();
            ResponseDto? responseDto = await _couponService.GetCouponByIdAsync(id);
            if (responseDto != null && responseDto.IsSuccess)
            {
                objCouponsDto = JsonConvert.DeserializeObject<CouponsDto>(Convert.ToString(responseDto.Result));
            }
            else
            {
                TempData["error"] = responseDto.Message;
            }
            return View(objCouponsDto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CouponsDto couponsDto)
        {
            couponsDto.CouponPicture = new byte[0];
            ResponseDto? responseDto = await _couponService.UpdatedCouponAsync(couponsDto);
            if(responseDto!=null && responseDto.IsSuccess)
            {
                TempData["success"] = responseDto.Message;
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = responseDto.Message;
            }
            return View(couponsDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            CouponsDto objCouponsDto = new CouponsDto();
            ResponseDto? responseDto = await _couponService.GetCouponByIdAsync(id);
            if (responseDto != null && responseDto.IsSuccess)
            {
                objCouponsDto = JsonConvert.DeserializeObject<CouponsDto>(Convert.ToString(responseDto.Result));
            }
            else
            {
                TempData["error"] = responseDto.Message;
            }
            return View(objCouponsDto);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CouponsDto couponsDto)
        {
            ResponseDto? responseDto = await _couponService.DeleteCouponAsync(couponsDto.Id);
            if (responseDto != null && responseDto.IsSuccess)
            {
                TempData["success"] = responseDto.Message;
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = responseDto.Message;
            }
            return View(couponsDto);
        }
    }
}

ShoppingCart.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ShoppingCart.Web.Models;
using ShoppingCart.Web.Service.IService;
using ShoppingCart.Web.Utility;
using System.IdentityModel.Tokens.Jwt;
using System.Threading.Tasks;

namespace ShoppingCart.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        public OrderController(IOrderService orderService)
        {
            this._orderService = orderService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAll(string? status)
        {
            IEnumerable<OrderHeaderDto> list;
            string userId = null;
            if (!User.IsInRole(StaticData.RoleAdmin))
            {
                userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
            }
            ResponseDto response = _orderService.GetAllOrder(userId).GetAwaiter().GetResult();
            if (response != null && response.IsSuccess)
            {
               list = JsonConvert.DeserializeObject<List<OrderHeaderDto>>(Convert.ToString(response.Result));
               switch(status)
                {
                    case StaticData.Status_Approved:
                        list = list.Where(u => u.OrderStatus == status).ToList();
                        break;
                    case StaticData.Status_ReadyForPickup:
                        list = list.Where(u => u.OrderStatus == status).ToList();
                        break;
                    case StaticData.Status_Cancelled:
                        list = list.Where(u => u.OrderStatus == status).ToList();
                        break;
                    default:
                        break;
                }
            }
            else
            {
                list = new List<OrderHeaderDto>();
            }
            return Json(new { data = list });
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int orderId)
        {
            OrderHeaderDto orderHeaderDto = new OrderHeaderDto();
            string userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;

            ResponseDto response = _orderService.GetOrder(orderId).GetAwaiter().GetResult();
            if (response != null && response.IsSuccess)
            {
                orderHeaderDto = JsonConvert.DeserializeObject<OrderHeaderDto>(Convert.ToString(response.Result));
            }
            if (!User.IsInRole(StaticData.RoleAdmin) && userId != orderHeaderDto.UserId)
            {
                return NotFound();
            }
            return View(orderHeaderDto);
        }

        [HttpPost("ReadyForPickup")]
        public async Task<IActionResult> ReadyForPickup(int orderId)
        {
            ResponseDto response =await _orderService.UpdateOrderStatus(orderId,StaticData.Status_ReadyForPickup);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction("Index");
            }
            return RedirectToAction(nameof(Detail),new { orderId=orderId});
        }

        [HttpPost("CancelOrder")]
        public async Task<IActionResult> CancelOrder(int orderId)
        {
            ResponseDto response = await _orderService.UpdateOrderStatus(orderId, StaticData.Status_Cancelled);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction("Index");
            }
            return RedirectToAction(nameof(Detail), new { orderId = orderId });
        }

        [HttpPost("CompleteOrder")]
        public async Task<IActionResult> CompleteOrder(int orderId)
        {
            ResponseDto response = await _orderService.UpdateOrderStatus(orderId, StaticData.Status_Completed);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction("Index");
            }
            return RedirectToAction(nameof(Detail), new { orderId = orderId });
        }

        [HttpPost("ApproveOrder")]
        public async Task<IActionResult> ApproveOrder(int orderId)
        {
            ResponseDto response = await _orderService.UpdateOrderStatus(orderId, StaticData.Status_Approved);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction("Index");
            }
            return RedirectToAction(nameof(Detail), new { orderId = orderId });
        }
    }
}

ShoppingCart.Web/Views/Shared/_Layout.cshtml
@using ShoppingCart.Web.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingCart.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.3.2/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/ShoppingCart.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShoppingCart.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(StaticData.RoleAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="Coupon" asp-action="Index">Coupon</a></li>
                                    <li><a class="dropdown-item" asp-controller="Product" asp-action="Index">Product</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart-fill"></i> Cart
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Order" asp-action="Index">
                                <i class="bi bi-cart-fill"></i> Manage Order
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item"><a class="nav-link">Hello, @User.Identity.Name</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notification" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Love my ASP Dot Net Core Technology...
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/2.3.2/js/dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShoppingCart.Web/Views/Shared/_Notification.cshtml
@if (TempData["error"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        toastr.error('@TempData["error"]');
    </script>

}
@if (TempData["success"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        toastr.success('@TempData["success"]');
    </script>
}